# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:

  - name: 主页
    pageRef:
    weight: 1

  - name: 教学成果与奖项
    pageRef: EE-awards
    weight: 10

  - name: 平台与专业建设
    pageRef: EE-platforms
    weight: 20

  - name: 教学项目与改革
    pageRef: EE-reforms
    weight: 30

  - name: 学生培养与竞赛
    pageRef: EE-students
    weight: 40

  - name: 科研与人才/媒体
    pageRef: EE-research-media
    weight: 50

#
#  - name: Tour
#    url: tour
#    weight: 10
#
#  - name: 研究团队
#    url: people
#    weight: 11
#
#  - name: 团队愿景
#    url: value
#    weight: 12
#
#  - name: 研究简介
#    url: research-introduction
#    weight: 13
#
#  - name: News
#    url: post
#    weight: 20
#
#  - name: Events
#    url: event
#    weight: 40
#
#  - name: 学术论文
#    url: publication
#    weight: 50
#
#  - name: 科研项目
#    url: projects
#    weight: 51
#
#  - name: 招生指南
#    url: contact
#    weight: 60
